In [ ]:
import pandas as pd

data = pd.read_csv('dataset_comparison.csv')

data['ratio_0_1'] = data['class_0_proportion'] / data['class_1_proportion']

columns = ['Name', 'class_0_proportion', 'class_1_proportion', 'ratio_0_1', 'dataset_size', 'AUC']
data = data[columns]

data.to_csv('dataset_comp_adjust.csv', index=False)

data

,Name,class_0_proportion,class_1_proportion,ratio_0_1,dataset_size,AUC
0,AntDataset,0.812856,0.187144,4.343478,1229,0.736639
1,CassDataset,0.851780,0.148220,5.746736,2584,0.923415
2,CommonsDataset,0.929655,0.070345,13.215686,725,0.689452
3,LucenceDataset,0.631175,0.368825,1.711314,3259,0.866930
4,DerbyDataset,0.913271,0.086729,10.530233,2479,0.964227
5,JmeterDataset,0.751656,0.248344,3.026667,604,0.921633
6,MvnDataset,0.915129,0.084871,10.782609,813,0.902667
7,PhoenixDataset,0.824161,0.175839,4.687023,2235,0.883597
8,TomcatDataset,0.721951,0.278049,2.596491,1435,0.855077